all:
	gcc -g -O0 test.c \
		   utils/stack.h \
		   utils/stack.c \
		   utils/common.h \
		   utils/common.c \
		   utils/operation_shortcuts.c \
		   preparer/preparer.h \
		   preparer/preparer.c \
		   preparer/internal.c \
		   preparer/checks.c \
		   translator/translator.h \
		   translator/translator.c \
		   translator/processing.c \
		   translator/operations.c \
		   translator/checks.c \
		   calculator/calculator.h \
		   calculator/calculator.c \
		   calculator/internal.c \
		   -o test
